version: 2.1
jobs:
  build_docker_image:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and Push application Docker image
          command: |
            mkdir -p /tmp/artifacts \
            && docker buildx build \
                --progress=plain \
                -t scipoptsuite:latest \
                -f Dockerfile.musl-cross . \
                --output type=local,dest=/tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build:
    jobs:
      - build_docker_image
