name: build-binaries


# Authors:
# Mark Turner
# Mohammed Ghannam
# Stefan Vigerske
# Franziska Schloesser
# Julian Manns
# Michael Winkler
#
# This is the base workflow script for generating SCIP libraries.
# These libraries intended purpose is to be shipped with the various
# SCIP interfaces for different programming languages (e.g. Python and Rust).
# These libraries enable users of those interfaces to not have to install SCIP themselves outside of
# the traditional package managers of their preferred programming languages.
# For example, pip install pyscipopt will now install SCIP on the users machine directly.
#
# A major issue with the development of these scripts was to statically generate
# as many dependencies as possible. This way users require a minimal amount
# of system libraries to actually install via their preferred programming language.
# Any extensions to this script should keep this design philosophy in mind.
#
# Current support:
# Linux x86-64
# Linux AArch64
# MacOS x86-64
# MacOS ARM64
# Windows x86-64
#

on:
    workflow_dispatch:
        inputs:
            scip_version:
                type: string
                description: SCIP version to use
                required: true
                default: "9.0.0"
            soplex_version:
                type: string
                description: Soplex version to use
                required: true
                default: "7.0.0"
            ipopt_version:
                type: string
                description: IPOPT version to use
                required: true
                default: "3.14.12"

jobs:
    print-inputs:
      runs-on: ubuntu-latest
      steps:
          - name: Print inputs
            run: |
              echo "SCIP version: ${{github.event.inputs.scip_version}}"
              echo "Soplex version: ${{github.event.inputs.soplex_version}}"
              echo "IPOPT version: ${{github.event.inputs.ipopt_version}}"

    linux-build-binaries:
        strategy:
            matrix:
              include:
                - os: ubuntu-22.04
                  container: quay.io/pypa/manylinux2014_x86_64
                  id: ubuntu-x86-64
                - os: buildjet-2vcpu-ubuntu-2204-arm
                  container: quay.io/pypa/manylinux2014_aarch64
                  id: ubuntu-aarch64

        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}
        steps:
            - uses: actions/checkout@v3
            - name: Build and install SCIP
              run: |
                export SCIP_VERSION=$(echo "${{ github.event.inputs.scip_version }}" | tr -d '.')
                export SOPLEX_VERSION=$(echo "${{ github.event.inputs.soplex_version }}" | tr -d '.')
                export IPOPT_VERSION=${{ github.event.inputs.ipopt_version }}
                bash -x .github/workflows/scripts/linux.bash
            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/libscip-${{ matrix.id }}.zip
