name: Build And Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of SCIPOptSuite like #.#.#'
        required: true
        type: number

env:
  IMAGE_NAME: scipoptsuite
  REPOSITORY_NAME: scipoptsuite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker Tags
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ github.event.inputs.version }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        build-args: TAG=${{ github.event.inputs.version }}